version: "3"

services:
  app:
    build: .
    container_name: slashbinslash
    ports:
      - "3000:3000"
      - "9999:9999"
    volumes:
      - ./uploads:/app/uploads
      - ./stats.json:/app/stats.json
    restart: unless-stopped
    networks:
      - slashbin-network

networks:
  slashbin-network:
    driver: bridge
