#ifndef HTML_RESOURCES_H
#define HTML_RESOURCES_H

// Index HTML content
static const char * __attribute__((unused)) INDEX_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"    <head>\n"
"        <meta charset=\"UTF-8\" />\n"
"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"        <title>slashbinslash.sh</title>\n"
"        <link rel=\"stylesheet\" href=\"style.css\" />\n"
"    </head>\n"
"    <body>\n"
"        <div class=\"container\">\n"
"            <pre class=\"ascii-art\">\n"
"██╗██████╗ ██╗███╗   ██╗    ██╗███████╗██╗  ██╗\n"
"██╔╝██╔══██╗██║████╗  ██║   ██╔╝██╔════╝██║  ██║\n"
"██╔╝ ██████╔╝██║██╔██╗ ██║  ██╔╝ ███████╗███████║\n"
"██╔╝  ██╔══██╗██║██║╚██╗██║ ██╔╝  ╚════██║██╔══██║\n"
"██╔╝   ██████╔╝██║██║ ╚████║██╔╝   ███████║██║  ██║\n"
"╚═╝    ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═╝    ╚══════╝╚═╝  ╚═╝\n"
"                                               \n"
"        </pre>\n"
"            <div class=\"tagline\">~everything is temporary~</div>\n"
"\n"
"            <div class=\"upload-section\">\n"
"                <form id=\"upload-form\" enctype=\"multipart/form-data\">\n"
"                    <div class=\"file-input\">\n"
"                        <input type=\"file\" id=\"file\" name=\"file\" />\n"
"                        <button type=\"submit\">Upload</button>\n"
"                    </div>\n"
"                </form>\n"
"                <div id=\"result\" class=\"hidden\"></div>\n"
"            </div>\n"
"\n"
"            <div class=\"info-section\">\n"
"                <div class=\"info-block\">\n"
"                    <h3>To upload via curl:</h3>\n"
"                    <pre>curl -F \"file=@yourfile.txt\" http://localhost:3000/upload</pre>\n"
"                </div>\n"
"\n"
"                <div class=\"info-block\">\n"
"                    <h3>Info:</h3>\n"
"                    <ul>\n"
"                        <li>Files expire after 3 days</li>\n"
"                        <li>Maximum file size: 4GB</li>\n"
"                        <li>No registration required</li>\n"
"                    </ul>\n"
"                </div>\n"
"\n"
"                <div class=\"info-block\">\n"
"                    <p>Inspired by temp.sh, termbin.com, and pomf.se</p>\n"
"                    <p>\n"
"                        Code:\n"
"                        <a\n"
"                            href=\"https://github.com/yourusername/slashbinslash.sh\"\n"
"                            target=\"_blank\"\n"
"                            >GitHub</a\n"
"                        >\n"
"                    </p>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <script src=\"script.js\"></script>\n"
"    </body>\n"
"</html>\n";

// CSS content
static const char * __attribute__((unused)) STYLE_CSS =
"body {\n"
"    background: #000;\n"
"    color: #aaa;\n"
"    font-family: monospace;\n"
"    margin: 0;\n"
"    padding: 20px;\n"
"    display: flex;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".container {\n"
"    max-width: 800px;\n"
"    width: 100%;\n"
"}\n"
"\n"
".ascii-art {\n"
"    color: #0f0;\n"
"    text-align: center;\n"
"    font-size: 0.8em;\n"
"    line-height: 1;\n"
"    white-space: pre;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    overflow-x: auto;\n"
"}\n"
"\n"
".tagline {\n"
"    text-align: center;\n"
"    color: #0f0;\n"
"    margin-bottom: 30px;\n"
"    font-style: italic;\n"
"}\n"
"\n"
".upload-section {\n"
"    background: #111;\n"
"    border: 1px solid #333;\n"
"    padding: 20px;\n"
"    margin-bottom: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
".file-input {\n"
"    display: flex;\n"
"}\n"
"\n"
".file-input input {\n"
"    flex-grow: 1;\n"
"    padding: 8px;\n"
"    background: #222;\n"
"    border: 1px solid #444;\n"
"    color: #eee;\n"
"    border-radius: 4px 0 0 4px;\n"
"}\n"
"\n"
".file-input button {\n"
"    padding: 8px 16px;\n"
"    background: #333;\n"
"    color: #0f0;\n"
"    border: 1px solid #444;\n"
"    border-left: none;\n"
"    cursor: pointer;\n"
"    border-radius: 0 4px 4px 0;\n"
"}\n"
"\n"
".file-input button:hover {\n"
"    background: #444;\n"
"}\n"
"\n"
".info-section {\n"
"    margin-top: 30px;\n"
"}\n"
"\n"
".info-block {\n"
"    margin-bottom: 20px;\n"
"}\n"
"\n"
".info-block h3 {\n"
"    color: #0f0;\n"
"    border-bottom: 1px solid #333;\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
".info-block pre {\n"
"    background: #111;\n"
"    padding: 10px;\n"
"    border-radius: 4px;\n"
"    overflow-x: auto;\n"
"}\n"
"\n"
".info-block ul {\n"
"    list-style-type: none;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
".info-block li:before {\n"
"    content: \"> \";\n"
"    color: #0f0;\n"
"}\n"
"\n"
"a {\n"
"    color: #0f0;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"a:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"#result {\n"
"    margin-top: 15px;\n"
"    padding: 10px;\n"
"    background: #111;\n"
"    border: 1px solid #333;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#result.success {\n"
"    border-color: #070;\n"
"}\n"
"\n"
"#result.error {\n"
"    border-color: #700;\n"
"}\n"
"\n"
".hidden {\n"
"    display: none;\n"
"}\n"
"\n"
".file-url {\n"
"    word-break: break-all;\n"
"}\n";

// JavaScript content
static const char * __attribute__((unused)) SCRIPT_JS =
"document.addEventListener(\"DOMContentLoaded\", () => {\n"
"  const form = document.getElementById(\"upload-form\");\n"
"  const resultDiv = document.getElementById(\"result\");\n"
"\n"
"  form.addEventListener(\"submit\", async (e) => {\n"
"    e.preventDefault();\n"
"\n"
"    const fileInput = document.getElementById(\"file\");\n"
"    if (!fileInput.files.length) {\n"
"      showResult(\"Please select a file\", \"error\");\n"
"      return;\n"
"    }\n"
"\n"
"    const formData = new FormData();\n"
"    formData.append(\"file\", fileInput.files[0]);\n"
"\n"
"    try {\n"
"      showResult(\"Uploading...\", \"info\");\n"
"\n"
"      const response = await fetch(\"/upload\", {\n"
"        method: \"POST\",\n"
"        body: formData,\n"
"      });\n"
"\n"
"      if (!response.ok) {\n"
"        throw new Error(\n"
"          `Server returned ${response.status}: ${await response.text()}`\n"
"        );\n"
"      }\n"
"\n"
"      const data = await response.json();\n"
"\n"
"      // Display success message with the file URL\n"
"      showResult(\n"
"        `\n"
"                <p>File uploaded successfully!</p>\n"
"                <p>URL: <a href=\"${data.url}\" target=\"_blank\" class=\"file-url\">${data.url}</a></p>\n"
"                <p>Size: ${formatFileSize(data.size)}</p>\n"
"                <p>Expires: ${new Date(data.expires).toLocaleString()}</p>\n"
"            `,\n"
"        \"success\"\n"
"      );\n"
"\n"
"      // Clear the file input\n"
"      fileInput.value = \"\";\n"
"    } catch (error) {\n"
"      showResult(`Upload failed: ${error.message}`, \"error\");\n"
"    }\n"
"  });\n"
"\n"
"  function showResult(message, type) {\n"
"    resultDiv.innerHTML = message;\n"
"    resultDiv.className = type; // Set class based on message type\n"
"    resultDiv.classList.remove(\"hidden\");\n"
"  }\n"
"\n"
"  function formatFileSize(bytes) {\n"
"    if (bytes < 1024) return bytes + \" bytes\";\n"
"    else if (bytes < 1048576) return (bytes / 1024).toFixed(1) + \" KB\";\n"
"    else if (bytes < 1073741824) return (bytes / 1048576).toFixed(1) + \" MB\";\n"
"    else return (bytes / 1073741824).toFixed(1) + \" GB\";\n"
"  }\n"
"});\n";

#endif // HTML_RESOURCES_H
